name: covid-19
channels:
  - defaults
dependencies:
  - ipykernel=5.1.4
  - matplotlib=3.1.3
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=0.25.3
  - pyarrow=0.13.0
  - pylint=2.4.4
  - python=3.7.6
  - scipy=1.4.1